### ISSUE TITLE
 Plugin did not respond

### ISSUE THREAD

**Issue by drymek** [ovh/terraform-provider-ovh#211]
### Terraform Version

Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/ovh/ovh v0.15.0

### Affected Resource(s)
- ovh_domain*

### Terraform Configuration Files
```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/ovh/ovh" {
  version = "0.15.0"
  hashes = [
    "h1:rh7PGMysbkMfqBSf2CFoItKr7fF9hS7ZAIsZp0eOCxE=",
    "zh:122172ff264ce8adfdd21af53b2a3bdf612f467aa24a44d3c517df05711d9324",
    "zh:255e029721057a9f7e284f072600b1ee219abbcaf60be505b8af164a0bf85f12",
    "zh:2db9a0c41062e8bfa51573f7cf584a82aa41e4d58b4e875dac993c08817558c3",
    "zh:2f399c684f0d557b38dd5471d1f1827592260e2fb0c5380b7b6db7e5f58eb29d",
    "zh:38fc5d0c2b0c5a549881b0ae942648f0b8542252533a6c7afcb2d6aeef003584",
    "zh:4949c7ed30e074c0f5f4489c73a1e1262919e7fb95337b1ffcb2ef2e65211a1b",
    "zh:4e9577d2099953a7aa31dca1dc31fdeeb57835e22b82f97b3f14056d8b907cb4",
    "zh:6f9a40171e3b9be0c7640bbe7b994cad613779528306d6a3b922e773357abd2d",
    "zh:7211debe573bd46d9e9ef10d60215ca8f3404baec437862e335945dcf798302d",
    "zh:73ce6df8810fa7f427814f4878afe1841c554c2f5021ed56affc0593ef538958",
    "zh:9aeb3b5b991cdc58cfc6a0c55ce71ebffad0cc2d906f876c4ebe40d0ed28b929",
    "zh:9f1d3628318c2059c6baa38a6156b3c06f3c34f43720228a9bb30bbb15844ba6",
    "zh:d38a2ad0809adcd2f3b95b5a8764bbdd4d1f96300951e050d578250152e459e9",
  ]
}
```

### Debug Output
```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-ovh_v0.15.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x196898f]

goroutine 133 [running]:
github.com/ovh/terraform-provider-ovh/ovh.resourceOvhDomainZoneRecordRead(0xc00028d680, 0x1aa35e0, 0xc00071e150, 0x22bc6f0, 0xc0001ef200)
	github.com/ovh/terraform-provider-ovh/ovh/resource_domain_zone_record.go:166 +0xcf
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0000e3a40, 0x1d4b6e8, 0xc0001575c0, 0xc00028d680, 0x1aa35e0, 0xc00071e150, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000e3a40, 0x1d4b6e8, 0xc0001575c0, 0xc00066d5e0, 0x1aa35e0, 0xc00071e150, 0xc00000e400, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c120, 0x1d4b6e8, 0xc0001575c0, 0xc000157600, 0xc0001575c0, 0x100b665, 0x1b31d60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00041d960, 0x1d4b790, 0xc0001575c0, 0xc0009f3f20, 0xc00041d960, 0xc00077ff50, 0xc0009a8ba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x1b6daa0, 0xc00041d960, 0x1d4b790, 0xc00077ff50, 0xc0009f3ec0, 0x0, 0x1d4b790, 0xc00077ff50, 0xc0006b1290, 0xa6)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000331500, 0x1d544d8, 0xc000682600, 0xc00020e300, 0xc00090e540, 0x227d650, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000331500, 0x1d544d8, 0xc000682600, 0xc00020e300, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000a80e0, 0xc000331500, 0x1d544d8, 0xc000682600, 0xc00020e300)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-ovh_v0.15.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue
```

### Expected Behavior
It's output from `terraform plan`, it should display planned actions

### Actual Behavior
Above error occured

### Steps to Reproduce
I have tfstate file created by the old version of terraform. After upgrade I've never been able to run `plan` properly

**Comment by Xaelias** [comment]
> Hi,
> 
> I tried this morning to reimport my domain - seems record id changed overtime. So previous record lead to plugin crashing but once I get new id from OVH API and import resource with new id, it works as expected.
> 
> Check via https://api.ovh.com/console/#/domain/zone/%7BzoneName%7D/record#GET
> 
> And update accordingly ;-)

Welp this kind of make the terraform plugin completely useless ><

**Comment by amstuta** [comment]
@drymek sorry for this late answer, do you still have this issue with a recent version of the provider ? If so, could you share your main.tf so that we have a reproducer ?

**Comment by drymek** [comment]
Hi @amstuta, it was 2.5 years ago. To be honest I hardly remember which project it was.
Today I use a free Hetzner DNS service to manage my domains. 

Sorry, but today I'm not able to help with this issue.

**Comment by amstuta** [comment]
Thanks for your answer @drymek, I'll close the issue then.
